### ISSUE TITLE
Content not loading because of insecure websocket endpoint

### ISSUE THREAD

**Issue by jeroenpardon** [viktorstrate/photoview#12]
I'm trying to make photoview accessible through my reverse proxy (nginx). The location is loaded, however the content is not. My browser's inspector gives me the error below.

I don't really know much about websockets and I have tried out a couple of things I could find, but none worked. So, I am not sure if this is something you could or should do something about. Is it possible to make the endpoint available over WSS?

Or maybe someone already knows a solution?

(Real domain name redacted in the error below)

```
GRAPHQL ENDPOINT http://192.168.1.20:8080/api/graphql
client.ts:545 Mixed Content: The page at 'https://photos.example.com/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://192.168.1.20:8080/api/graphql'. This request has been blocked; this endpoint must be available over WSS.
e.connect @ client.ts:71
e @ client.ts:71
r @ webSocketLink.ts:30
parcelRequire.OaXc.@babel/runtime/helpers/toConsumableArray @ apolloClient.js:121
f @ ItemHeader.js:41
p @ ItemHeader.js:41
parcelRequire.Focm.react @ index.js:21
f @ ItemHeader.js:41
parcelRequire.J4Nk @ ItemHeader.js:41
(anonymous) @ ItemHeader.js:41
ItemDescription.js:41 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at e.connect (https://photos.example.com/src.0fd3d741.js:1619:9265)
    at new e (https://photos.example.com/src.0fd3d741.js:1619:2980)
    at new r (https://photos.example.com/src.0fd3d741.js:1621:324)
    at Object.parcelRequire.OaXc.@babel/runtime/helpers/toConsumableArray (https://photos.example.com/src.0fd3d741.js:1627:1442)
    at f (https://photos.example.com/src.0fd3d741.js:1:468)
    at p (https://photos.example.com/src.0fd3d741.js:1:544)
    at Object.parcelRequire.Focm.react (https://photos.example.com/src.0fd3d741.js:1631:132)
    at f (https://photos.example.com/src.0fd3d741.js:1:468)
    at parcelRequire.J4Nk (https://photos.example.com/src.0fd3d741.js:1:771)
    at https://photos.example.com/src.0fd3d741.js:1:1023
parcelRequire.J4Nk @ ItemHeader.js:41
(anonymous) @ ItemHeader.js:41
```

**Comment by viktorstrate** [comment]
Can you post your `docker-compose.yml` file and nginx config?

I can later today post the config of the demo site which is running over https and wss.

**Comment by jeroenpardon** [comment]
Sure , my compose file is the same as the original. Nginx config below

If you can post your config later today, don't waste time looking into my config though, I'm not in a hurry ;)

```
server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name photos.example.com;

        location / {
                proxy_pass http://192.168.1.20:8080;
                #auth_request /oauth2/auth;
                #eror_page 401 = /oauth2/sign_in;
        }

        client_max_body_size 50m;

        include /config/nginx/proxy.conf;
        include /config/nginx/ssl.conf;
        #include /config/nginx/oauth.conf;
        #include /config/nginx/cors.conf;
}
```

proxy.conf
```
add_header X-Robots-Tag none;
add_header X-Frame-Options "SAMEORIGIN" always;##
add_header X-XSS-Protection "1; mode=block" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Referrer-Policy "no-referrer-when-downgrade" always;
add_header Content-Security-Policy "default-src * data: 'unsafe-eval' 'unsafe-inline'" always;
add_header X-Forwarded-Proto $scheme;

add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;

proxy_set_header Host $host;
proxy_set_header X-Forwarded-Host $server_name;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Ssl on;

proxy_set_header X-Forwarded-Proto https;

#proxy_set_header X-Forwarded-Proto $scheme;
proxy_read_timeout  90;
proxy_redirect http://127.0.0.1:5000 https://$host;
```

ssl.conf
```
# session settings
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:50m;
ssl_session_tickets off;

# Diffie-Hellman parameter for DHE cipher suites
ssl_dhparam /config/nginx/dhparams.pem;

# ssl certs
ssl_certificate /config/keys/letsencrypt/fullchain.pem;
ssl_certificate_key /config/keys/letsencrypt/privkey.pem;

# protocols
# using generated 2020-01-07, https://ssl-config.mozilla.org/#server=nginx&server-version=1.16.1-r4&config=intermediate&openssl-version=1.1.1d-r3
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
ssl_prefer_server_ciphers off;

# HSTS, remove # from the line below to enable HSTS
#add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

# OCSP Stapling
ssl_stapling on;
ssl_stapling_verify on;
resolver 127.0.0.11 valid=30s; # Docker DNS Server

# Enable TLS 1.3 early data
ssl_early_data on;
```

**Comment by viktorstrate** [comment]
I am currently using [Traefik](https://docs.traefik.io/) as my reverse proxy instead of nginx. Thats why I have all the `labels` tags. Also the api is served on a subdomain `api.photos.qpqp.dk` this is not necessary.

I think the most important thing is that `API_ENDPOINT`, `PUBLIC_ENDPOINT` and `GRAPHQL_ENDPOINT` are set to the publicly accessed urls, if they are set to the default `localhost` it will only work over localhost.

I can also see, that in the nginx proxy used in the default docker-compose.yml has special proxy headers to handle websockets (see below). You might have to add them in your `server` -> `location /` block.

https://github.com/viktorstrate/photoview/blob/5cee5d8dea847db66ea33d8b786baabb73d7692f/docker/nginx-proxy/default.conf#L11-L13

**docker-compose.yml for the production demo site**

```yml
version: "3"

services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photo-secret
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - internal
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: ./api
    restart: always
    expose:
      - 4001
    depends_on:
      - db
    networks:
      - web
      - internal
    environment:
      - MYSQL_URL=photoview:photo-secret@tcp(db)/photoview
      - PHOTO_CACHE=/app/cache
      # Change This: The publicly exposed url for the api
      # For example if the server is available from the domain example.com,
      # change this value to http://example.com/api
      - API_ENDPOINT=https://api.photos.qpqp.dk/
      - PUBLIC_ENDPOINT=https://photos.qpqp.dk/
      - API_LISTEN_PORT=4001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photoview-api.rule=Host(`api.photos.qpqp.dk`)"
      - "traefik.http.routers.photoview-api.entrypoints=http"
      # TLS
      - "traefik.http.routers.photoview-api.middlewares=https-redirect@file"
      - "traefik.http.routers.photoview-api-secure.entrypoints=https"
      - "traefik.http.routers.photoview-api-secure.rule=Host(`api.photos.qpqp.dk`)"
      - "traefik.http.routers.photoview-api-secure.tls=true"
      - "traefik.http.routers.photoview-api-secure.tls.certresolver=http"
      - "traefik.http.routers.photoview-api-secure.service=api-photoview"
    volumes:
      # Change This: Link photo paths from the host machine
      # Change this to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /storage/:/photos:ro
      - api_cache:/app/cache

  ui:
    build:
      context: ./ui
      args:
        # Change This: The publicly exposed url for the graphql api
        # For example if the server is available from the domain example.com,
        # change this value to http://example.com/api/graphql
        GRAPHQL_ENDPOINT: https://api.photos.qpqp.dk/graphql
    restart: always
    networks:
      - web
      - internal
    expose:
      - 80
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photoview.rule=Host(`photos.qpqp.dk`)"
      - "traefik.http.routers.photoview.entrypoints=http"
      # TLS
      - "traefik.http.routers.photoview.middlewares=https-redirect@file"
      - "traefik.http.routers.photoview-secure.entrypoints=https"
      - "traefik.http.routers.photoview-secure.rule=Host(`photos.qpqp.dk`)"
      - "traefik.http.routers.photoview-secure.tls=true"
      - "traefik.http.routers.photoview-secure.tls.certresolver=http"
      - "traefik.http.routers.photoview-secure.service=ui-photoview"

volumes:
  db_data:
  api_cache:

networks:
  web:
    external: true
  internal:
    external: false
```
