### ISSUE TITLE
Photoview behind Traefik v2

### ISSUE THREAD

**Issue by kucrut** [viktorstrate/photoview#54]
I can't seem to be able to run Photoview behind traefik. It's just stuck loading and timed out.

Here's my compose file:

```yml
version: "3"

services:
  db:
    container_name: photoview-db
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photo-secret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql

  photoview:
    container_name: photoview-app
    image: viktorstrate/photoview:latest
    restart: always
    depends_on:
      - db

    environment:
      - MYSQL_URL=photoview:photo-secret@tcp(db)/photoview
      - API_LISTEN_IP=photoview
      - API_LISTEN_PORT=80
      - PHOTO_CACHE=/app/cache

      # Change This: The publicly exposed url
      # For example if the server is available from the domain example.com,
      # change this value to http://example.com/
      - API_ENDPOINT=https://my.domain.tld/api/
      - PUBLIC_ENDPOINT=https://my.domain.tld/

    volumes:
      - api_cache:/app/cache

      # Change this to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /tmp/photos:/photos:ro

    labels:
      - "traefik.http.routers.photoview.entrypoints=http"
      - "traefik.http.routers.photoview.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.photoview.rule=Host(`my.domain.tld`)"
      - "traefik.http.routers.photoview-secure.entrypoints=https"
      - "traefik.http.routers.photoview-secure.rule=Host(`my.domain.tld`)"
      - "traefik.http.routers.photoview-secure.tls=true"
      - "traefik.http.routers.photoview-secure.tls.certresolver=letsencrypt"

volumes:
  db_data:
  api_cache:
```
